### ISSUE TITLE
Full status bar is not centered in Cropped mode

### ISSUE THREAD

**Issue by DrUm78** [StupidHoroscope/fks-eduke32#5]
Tested on my Q36 Mini with 1.0 OPK and official OS 2.3.0.

The full status bar is not centered in Cropped mode (compare screenshots between Stretched and Cropped modes). It should be cropped the same amount of pixels on each side.

Stretched:
![IMG_0234](https://user-images.githubusercontent.com/46139740/160132383-a20e3464-e6c8-4321-9dce-dc591c1ed3f9.PNG)

Cropped:
![IMG_0235](https://user-images.githubusercontent.com/46139740/160132430-9d5fa543-3248-484b-a7d1-1597bac6b2fd.PNG)

**Comment by StupidHoroscope** [comment]
Fixed in v1.1
